import { 
  Timer as TimerIcon,
  Lightbulb as HintIcon,
  X as MistakeIcon,
  Pause as PauseIcon,
  Play as PlayIcon,
  Home as HomeIcon,
  Eraser as EraseIcon,
  Pen as PencilIcon,
  Trophy as TrophyIcon,
  Wand2 as MagicIcon,
  User as PlayerIcon,
  Settings as SystemIcon,
  Settings as SettingsIcon,
  BarChart2 as StatsIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  CheckCircle2 as CheckCircleIcon,
  Volume2 as SoundOnIcon,
  VolumeX as SoundOffIcon,
  Vibrate as VibrateIcon,
  Zap as InstantCheckIcon,
  EyeOff as NoCheckIcon,
  Power as PowerIcon
} from 'lucide-react';

export {
  TimerIcon,
  HintIcon,
  MistakeIcon,
  PauseIcon,
  PlayIcon,
  HomeIcon,
  EraseIcon,
  PencilIcon,
  TrophyIcon,
  MagicIcon,
  PlayerIcon,
  SystemIcon,
  SettingsIcon,
  StatsIcon,
  SunIcon,
  MoonIcon,
  CheckCircleIcon,
  SoundOnIcon,
  SoundOffIcon,
  VibrateIcon,
  InstantCheckIcon,
  NoCheckIcon,
  PowerIcon
};
